# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marco/ProyectosQt/ProyectoFinalCG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marco/ProyectosQt/ProyectoFinalCG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marco/ProyectosQt/ProyectoFinalCG/CMakeFiles /home/marco/ProyectosQt/ProyectoFinalCG/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marco/ProyectosQt/ProyectoFinalCG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProyectoFinalCG

# Build rule for target.
ProyectoFinalCG: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProyectoFinalCG
.PHONY : ProyectoFinalCG

# fast build rule for target.
ProyectoFinalCG/fast:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/build
.PHONY : ProyectoFinalCG/fast

Geometry.o: Geometry.cpp.o

.PHONY : Geometry.o

# target to build an object file
Geometry.cpp.o:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/Geometry.cpp.o
.PHONY : Geometry.cpp.o

Geometry.i: Geometry.cpp.i

.PHONY : Geometry.i

# target to preprocess a source file
Geometry.cpp.i:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/Geometry.cpp.i
.PHONY : Geometry.cpp.i

Geometry.s: Geometry.cpp.s

.PHONY : Geometry.s

# target to generate assembly for a file
Geometry.cpp.s:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/Geometry.cpp.s
.PHONY : Geometry.cpp.s

OBJFile.o: OBJFile.cpp.o

.PHONY : OBJFile.o

# target to build an object file
OBJFile.cpp.o:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/OBJFile.cpp.o
.PHONY : OBJFile.cpp.o

OBJFile.i: OBJFile.cpp.i

.PHONY : OBJFile.i

# target to preprocess a source file
OBJFile.cpp.i:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/OBJFile.cpp.i
.PHONY : OBJFile.cpp.i

OBJFile.s: OBJFile.cpp.s

.PHONY : OBJFile.s

# target to generate assembly for a file
OBJFile.cpp.s:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/OBJFile.cpp.s
.PHONY : OBJFile.cpp.s

Topology.o: Topology.cpp.o

.PHONY : Topology.o

# target to build an object file
Topology.cpp.o:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/Topology.cpp.o
.PHONY : Topology.cpp.o

Topology.i: Topology.cpp.i

.PHONY : Topology.i

# target to preprocess a source file
Topology.cpp.i:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/Topology.cpp.i
.PHONY : Topology.cpp.i

Topology.s: Topology.cpp.s

.PHONY : Topology.s

# target to generate assembly for a file
Topology.cpp.s:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/Topology.cpp.s
.PHONY : Topology.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ProyectoFinalCG.dir/build.make CMakeFiles/ProyectoFinalCG.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ProyectoFinalCG"
	@echo "... Geometry.o"
	@echo "... Geometry.i"
	@echo "... Geometry.s"
	@echo "... OBJFile.o"
	@echo "... OBJFile.i"
	@echo "... OBJFile.s"
	@echo "... Topology.o"
	@echo "... Topology.i"
	@echo "... Topology.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

