#include "OBJFile.h"


//Marco Antonio Quiña Mamani


OBJFile::OBJFile()
{

}
void OBJFile::readFileOBJ(const std::string& filename) {
    std::ifstream fileStream{ filename, std::ios_base::in };
    if (fileStream.is_open())
    {
        while (!fileStream.eof())
        {
            std::string line;
            getline(fileStream, line);
            std::stringstream lineStream{ line };

            std::string firstSymbol;
            lineStream >> firstSymbol;
            if (firstSymbol == "v")
            {
                float x,y,z;
                lineStream >> x >> y >> z;
                glm::vec3 vertice(x, y, z);
                m_VertexPositions.emplace_back(vertice);
            }
            else if (firstSymbol == "vn")
            {
                float x,y,z;
                lineStream >> x >> y >> z;
                glm::vec3 normal(x, y, z);
                m_Normals.emplace_back(normal);
            }
            else if (firstSymbol == "f")
            {
                std::string vertex1, vertex2, vertex3;
                unsigned int vertexIndex[3] = {0,0,0};
                unsigned int uvIndex[3]     = {0,0,0};
                unsigned int normalIndex[3] = {0,0,0};

                lineStream >> vertex1 >> vertex2 >> vertex3;
                auto c_vertex1 = vertex1.c_str();
                auto c_vertex2 = vertex2.c_str();
                auto c_vertex3 = vertex3.c_str();

                int  matches = 0;
                matches += std::sscanf(c_vertex1, "%d/%d/%d", &vertexIndex[0], &uvIndex[0], &normalIndex[0]);
                matches += std::sscanf(c_vertex2, "%d/%d/%d", &vertexIndex[1], &uvIndex[1], &normalIndex[1]);
                matches += std::sscanf(c_vertex3, "%d/%d/%d", &vertexIndex[2], &uvIndex[2], &normalIndex[2]);

                //std::cout<<"AQUI "<<vertexIndex[0]<<" "<<uvIndex[0]<<" "<<normalIndex[0]<<" "<<std::endl;
                //std::cout<<matches<<std::endl;

                m_IndicesVertex.push_back(vertexIndex[0]);
                m_IndicesVertex.push_back(vertexIndex[1]);
                m_IndicesVertex.push_back(vertexIndex[2]);
                m_IndicesUvs.push_back(uvIndex[0]);
                m_IndicesUvs.push_back(uvIndex[1]);
                m_IndicesUvs.push_back(uvIndex[2]);
                m_IndicesNormals.push_back(normalIndex[0]);
                m_IndicesNormals.push_back(normalIndex[1]);
                m_IndicesNormals.push_back(normalIndex[2]);
            }
        }

        for (unsigned int i = 0; i < m_IndicesVertex.size(); ++i)
        {
            /* code */
        }
        

    }
}
void OBJFile::writeFrames(const std::string& directory, unsigned index)
{
    std::string fileName  = directory+"/frame_"+std::to_string(index)+".obj";

    std::ofstream frame(fileName);
    if (!frame.is_open())
    {
        std::cerr<<"Error opening "<<fileName <<std::endl;
        return;
    }
    frame <<"# Generated by Visualization Toolkit"<<std::endl;
    for(auto it = m_VertexPositions.begin(); it != m_VertexPositions.end(); ++it)
    {
        frame <<"v "<<std::setprecision(20)<<it->x<<" "<<it->y<<" "<<it->z<<std::endl;
    }

    for(unsigned i = 0; i < m_IndicesVertex.size(); i+=3) {

        frame<<"f "<<m_IndicesVertex[i]<<" "<<m_IndicesVertex[i+1]<<" "<<m_IndicesVertex[i+2]<<std::endl;

    }
}

void OBJFile::writeFramesInVTK(const std::string& directory, unsigned index)
{
    std::string fileName  = directory+"/frame_"+std::to_string(index)+".vtk";

    std::ofstream frame (fileName);

    if (!frame.is_open())
    {
        std::cerr<<"Error opening "<<fileName <<std::endl;
        return;
    }

    //headers
    frame <<"# vtk DataFile Version 2.0"<<std::endl;
    frame<<"Particle system"<<std::endl;
    frame<<"ASCII"<<std::endl;
    frame<<"DATASET UNSTRUCTURED_GRID"<<std::endl;
    frame<<"POINTS "<< m_VertexPositions.size()<< " float"<< std::endl;

    for(auto it = m_VertexPositions.begin(); it != m_VertexPositions.end(); ++it)
    {

        frame <<it->x<<" "<<it->y<<" "<<it->z<<std::endl;
    }

    frame<<"CELLS "<< m_VertexPositions.size()<< " "<< m_VertexPositions.size()*2<< std::endl;

    for(unsigned i=0;i<m_VertexPositions.size();++i)
    {
        frame<<1<<" "<<i<<std::endl;

    }

    frame<<"CELL_TYPES "<< m_VertexPositions.size()<< std::endl;
    for(unsigned i=0;i<m_VertexPositions.size();++i)
    {
        frame<<1<<std::endl;
    }

    frame<<"CELL_DATA "<< m_VertexPositions.size()<< std::endl;
    frame<<"SCALARS cell_scalars float 1"<< std::endl;
    frame<<"LOOKUP_TABLE ParticleColors "<< std::endl;
    for(unsigned i=0;i<m_VertexPositions.size();++i)
    {
        frame<< "0.0" <<std::endl;
    }

    //Green color
    frame<<"LOOKUP_TABLE ParticleColors "<< m_VertexPositions.size()<< std::endl;
    for(unsigned i=0;i<m_VertexPositions.size();++i)
    {
        frame<< "0.0 1.0 0.0 1.0" <<std::endl;
    }
}

OBJFile::Vertices& OBJFile::GetVertices() {
    return m_VertexPositions;
}

OBJFile::Normals& OBJFile::GetNormals() {
    return m_Normals;
}

OBJFile::Uvs& OBJFile::GetUvs() {
    return m_Uvs;
}

OBJFile::IndicesVertices& OBJFile::GetIndicesVertices() {
    return m_IndicesVertex;
}

OBJFile::IndicesUvs& OBJFile::GetIndicesUvs() {
    return m_IndicesUvs;
}

OBJFile::IndicesNormals& OBJFile::GetIndicesNormals() {
    return m_IndicesNormals;
}
